"""
This type stub file was generated by pyright.
"""

from Levenshtein import *

"""
StringMatcher.py

ported from python-Levenshtein
[https://github.com/miohtama/python-Levenshtein]
License available here: https://github.com/miohtama/python-Levenshtein/blob/master/COPYING
"""
class StringMatcher:
    """A SequenceMatcher-like class built on the top of Levenshtein"""
    def __init__(self, isjunk=..., seq1=..., seq2=...) -> None:
        ...
    
    def set_seqs(self, seq1, seq2): # -> None:
        ...
    
    def set_seq1(self, seq1): # -> None:
        ...
    
    def set_seq2(self, seq2): # -> None:
        ...
    
    def get_opcodes(self): # -> _OpcodesList:
        ...
    
    def get_editops(self): # -> _EditopsList:
        ...
    
    def get_matching_blocks(self): # -> _MatchingBlocks:
        ...
    
    def ratio(self): # -> float:
        ...
    
    def quick_ratio(self): # -> float:
        ...
    
    def real_quick_ratio(self): # -> float:
        ...
    
    def distance(self): # -> int:
        ...
    


